//! Bakes the cue sounds into the binary at compile time.
//!
//! The shipped program has no asset directory and no libopus: the Ogg Opus files the main
//! app serves to browsers are decoded here, at build time, and the resulting PCM is
//! embedded. `ogg` and `opus` are build-dependencies only, so they link into this script
//! and never into the binary.

use std::env;
use std::fs;
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};

/// The cues the operator window plays in unfiltered mode. `beep-low.opus` belongs to the
/// Phone view's camera-filter mode, which the Cue Tray does not reproduce, and
/// `four`/`five` are shipped but unused — the countdown only ever reaches three.
const CUES: &[(&str, &str)] = &[
    ("ONE", "one.opus"),
    ("TWO", "two.opus"),
    ("THREE", "three.opus"),
    ("BEEP", "beep.opus"),
];

const SAMPLE_RATE: u32 = 48_000;
/// Longest Opus frame is 120 ms; at 48 kHz mono that is 5760 samples.
const MAX_FRAME_SAMPLES: usize = 5760;

fn main() {
    let audio_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../resources/audio");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let mut generated = String::from(
        "// @generated by build.rs — do not edit.\n\
         pub const SAMPLE_RATE: u32 = 48_000;\n\
         pub const CHANNELS: u16 = 1;\n\n",
    );

    for (constant, filename) in CUES {
        let source = audio_dir.join(filename);
        println!("cargo:rerun-if-changed={}", source.display());

        let pcm = decode(&source);
        let pcm_path = out_dir.join(format!("{filename}.pcm"));
        let mut bytes = Vec::with_capacity(pcm.len() * 2);
        for sample in &pcm {
            bytes.extend_from_slice(&sample.to_le_bytes());
        }
        fs::File::create(&pcm_path)
            .and_then(|mut f| f.write_all(&bytes))
            .unwrap_or_else(|e| panic!("writing {}: {e}", pcm_path.display()));

        generated.push_str(&format!(
            "/// {filename}: {} samples ({} ms)\n\
             pub static {constant}_PCM: &[u8] = include_bytes!(r\"{}\");\n\n",
            pcm.len(),
            pcm.len() as u32 * 1000 / SAMPLE_RATE,
            pcm_path.display(),
        ));
    }

    fs::write(out_dir.join("cues.rs"), generated).expect("writing cues.rs");
}

/// Demuxes one Ogg Opus file and decodes it to 48 kHz mono `i16`.
///
/// A missing or malformed cue fails the build rather than producing a silent tray: a tray
/// that plays nothing looks identical to one that is merely disconnected.
fn decode(path: &Path) -> Vec<i16> {
    let raw = fs::read(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let mut reader = ogg::PacketReader::new(Cursor::new(raw));

    let head = reader
        .read_packet_expected()
        .unwrap_or_else(|e| panic!("{}: no OpusHead packet: {e}", path.display()));
    let (channels, pre_skip) = parse_opus_head(&head.data, path);

    // OpusTags. Present in every well-formed stream; discarded.
    reader
        .read_packet_expected()
        .unwrap_or_else(|e| panic!("{}: no OpusTags packet: {e}", path.display()));

    let mut decoder = opus::Decoder::new(SAMPLE_RATE, opus::Channels::Mono)
        .unwrap_or_else(|e| panic!("{}: opus decoder: {e}", path.display()));

    let mut pcm = Vec::new();
    let mut frame = vec![0i16; MAX_FRAME_SAMPLES];
    let mut last_granule = 0u64;

    while let Some(packet) = reader
        .read_packet()
        .unwrap_or_else(|e| panic!("{}: reading packet: {e}", path.display()))
    {
        let decoded = decoder
            .decode(&packet.data, &mut frame, false)
            .unwrap_or_else(|e| panic!("{}: decoding: {e}", path.display()));
        pcm.extend_from_slice(&frame[..decoded]);
        last_granule = packet.absgp_page();
    }

    // Opus encoders prepend priming samples and pad the tail to a frame boundary. Playing
    // them back produces an audible click at the head of every cue and a few ms of garbage
    // at the end — cheap to miss on a laptop, obvious in a quiet control room.
    let pre_skip = pre_skip as usize;
    assert!(
        pcm.len() > pre_skip,
        "{}: shorter than its {pre_skip}-sample pre-skip",
        path.display()
    );
    pcm.drain(..pre_skip);

    let end = (last_granule as usize).saturating_sub(pre_skip);
    if end > 0 && end < pcm.len() {
        pcm.truncate(end);
    }

    assert_eq!(
        channels, 1,
        "{}: expected mono, got {channels} channels",
        path.display()
    );
    assert!(!pcm.is_empty(), "{}: decoded to nothing", path.display());
    assert!(
        pcm.iter().any(|&s| s.unsigned_abs() > 64),
        "{}: decoded to near-silence",
        path.display()
    );

    pcm
}

/// Returns `(channels, pre_skip)` from an OpusHead packet.
/// Layout: magic[8] version[1] channels[1] pre_skip[2 LE] input_rate[4] gain[2] mapping[1].
fn parse_opus_head(data: &[u8], path: &Path) -> (u8, u16) {
    assert!(
        data.len() >= 19 && &data[..8] == b"OpusHead",
        "{}: not an Ogg Opus stream",
        path.display()
    );
    (data[9], u16::from_le_bytes([data[10], data[11]]))
}
